# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(466, 345)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(100, 290, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.l_name = QtWidgets.QLabel(Dialog)
        self.l_name.setGeometry(QtCore.QRect(20, 31, 161, 20))
        self.l_name.setObjectName("l_name")
        self.l_burnlvl = QtWidgets.QLabel(Dialog)
        self.l_burnlvl.setGeometry(QtCore.QRect(20, 71, 161, 20))
        self.l_burnlvl.setObjectName("l_burnlvl")
        self.l_beans = QtWidgets.QLabel(Dialog)
        self.l_beans.setGeometry(QtCore.QRect(20, 111, 161, 20))
        self.l_beans.setObjectName("l_beans")
        self.l_descr = QtWidgets.QLabel(Dialog)
        self.l_descr.setGeometry(QtCore.QRect(20, 151, 161, 20))
        self.l_descr.setObjectName("l_descr")
        self.l_price = QtWidgets.QLabel(Dialog)
        self.l_price.setGeometry(QtCore.QRect(20, 191, 161, 20))
        self.l_price.setObjectName("l_price")
        self.l_vol = QtWidgets.QLabel(Dialog)
        self.l_vol.setGeometry(QtCore.QRect(20, 231, 161, 20))
        self.l_vol.setObjectName("l_vol")
        self.le_name = QtWidgets.QLineEdit(Dialog)
        self.le_name.setGeometry(QtCore.QRect(220, 30, 221, 24))
        self.le_name.setObjectName("le_name")
        self.le_burnlvl = QtWidgets.QLineEdit(Dialog)
        self.le_burnlvl.setGeometry(QtCore.QRect(220, 70, 221, 24))
        self.le_burnlvl.setObjectName("le_burnlvl")
        self.le_beans = QtWidgets.QLineEdit(Dialog)
        self.le_beans.setGeometry(QtCore.QRect(220, 110, 221, 24))
        self.le_beans.setObjectName("le_beans")
        self.le_descr = QtWidgets.QLineEdit(Dialog)
        self.le_descr.setGeometry(QtCore.QRect(220, 150, 221, 24))
        self.le_descr.setObjectName("le_descr")
        self.le_price = QtWidgets.QLineEdit(Dialog)
        self.le_price.setGeometry(QtCore.QRect(220, 190, 221, 24))
        self.le_price.setObjectName("le_price")
        self.le_vol = QtWidgets.QLineEdit(Dialog)
        self.le_vol.setGeometry(QtCore.QRect(220, 230, 221, 24))
        self.le_vol.setObjectName("le_vol")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.l_name.setText(_translate("Dialog", "Название сорта:"))
        self.l_burnlvl.setText(_translate("Dialog", "Степень обжарки (число):"))
        self.l_beans.setText(_translate("Dialog", "В зёрнах - 1/Молотый - 0:"))
        self.l_descr.setText(_translate("Dialog", "Описание вкуса:"))
        self.l_price.setText(_translate("Dialog", "Цена (число):"))
        self.l_vol.setText(_translate("Dialog", "Объём (число):"))
