# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1039, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tbl = QtWidgets.QTableWidget(self.centralwidget)
        self.tbl.setGeometry(QtCore.QRect(220, 20, 751, 501))
        self.tbl.setObjectName("tbl")
        self.tbl.setColumnCount(0)
        self.tbl.setRowCount(0)
        self.b_add = QtWidgets.QPushButton(self.centralwidget)
        self.b_add.setGeometry(QtCore.QRect(30, 90, 151, 31))
        self.b_add.setObjectName("b_add")
        self.b_edit = QtWidgets.QPushButton(self.centralwidget)
        self.b_edit.setGeometry(QtCore.QRect(30, 176, 151, 31))
        self.b_edit.setObjectName("b_edit")
        self.b_delete = QtWidgets.QPushButton(self.centralwidget)
        self.b_delete.setGeometry(QtCore.QRect(30, 260, 151, 31))
        self.b_delete.setObjectName("b_delete")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1039, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.b_add.setText(_translate("MainWindow", "Добавить"))
        self.b_edit.setText(_translate("MainWindow", "Изменить"))
        self.b_delete.setText(_translate("MainWindow", "Удалить"))
